# This file is auto-generated by the `evennia connections` wizard.
# Don't edit manually, your changes will be overwritten.

GAME_INDEX_ENABLED = True
GAME_INDEX_LISTING = \
{   'game_name': 'Evennia',
    'game_status': 'pre-alpha',
    'game_website': '',
    'listing_contact': 'Ironclaw@ironclaw.online',
    'long_description': 'Comming Soon',
    'short_description': 'Anthropomorphic Fantasy MUD - Visit the world of '
                         'Ironclaw!',
    'telnet_hostname': '',
    'telnet_port': '',
    'web_client_url': ''}